### ISSUE TITLE
Soft Tab Length in the core Language Yaml Settings won't stick

### ISSUE THREAD

**Issue by jpartain89** [atom/language-yaml#50] opened 2016-06-08 07:38 UTC
For some strange reason, the Tab Length option won't change to anything but whatever the primary Settings page's Tab Length is also set to.

This also seems to be occurring in every single package that has the Tab Length option. 

I'll delete the number and type in, say "2", and then either click out of it or hit tab, and the number will delete itself, flash "Default: 2" for a second and then "4" will appear once again.

**Comment by 50Wliu** [comment] 2016-06-08 12:52
This is a duplicate of atom/settings-view#774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-08 12:52 UTC
