### ISSUE TITLE
Failed to load a language-yaml package grammar

### ISSUE THREAD

**Issue by lythium** [atom/language-yaml#91] opened 2017-08-30 20:21 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [language-yaml](https://github.com/atom/language-yaml) package 0.30.0

### Stack Trace

Failed to load a language-yaml package grammar

```
At C:\Users\nikop\AppData\Local\atom\app-1.19.4\resources\app\node_modules\language-yaml\grammars\yaml.json: Unexpected token  in JSON at position 0 in C:\Users\nikop\AppData\Local\atom\app-1.19.4\resources\app\node_modules\language-yaml\grammars\yaml.json

SyntaxError: C:\Users\nikop\AppData\Local\atom\app-1.19.4\resources\app\node_modules\language-yaml\grammars\yaml.json: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseObject (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/season/lib/cson.js:58:25)
    at parseContents (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/season/lib/cson.js:106:22)
    at ~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/season/lib/cson.js:212:26
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at ~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/language-yaml/grammars/yaml.json:1:1
```

### Commands

```
  2x -0:38 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-minify 0.8.0 
autoprefixer 3.7.1 
color-picker 2.2.5 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.11 
git-plus 7.9.3 
split-diff 1.5.0 
svn 0.0.13 
tortoise-svn 0.5.1 
```

**Comment by 50Wliu** [comment] 2017-09-06 22:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-09-06 22:22 UTC
