### ISSUE TITLE
Comment color resets for long comment lines

### ISSUE THREAD

**Issue by mcandre** [atom/language-yaml#110] opened 2019-07-01 15:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The color for syntax highlighting comments, halts in the middle of a long comment line and resets to a different color.

### Steps to Reproduce

1. Write a YAML file with long lines (~2048 ASCII characters).
2. Comment the line.

**Expected behavior:**

The entire line is rendered with the user's preferred comment color.

**Actual behavior:**

A significant remainder of the line is highlighted with a different color.

**Reproduces how often:**

Always

### Versions

```console
$ apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.15
git 2.18.0

$ atom --version
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by calebmeyer** [comment] 2019-07-01 20:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/1667. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by calebmeyer** 2019-07-01 20:47 UTC
Labels: duplicate
