### ISSUE TITLE
Tab length setting does not work

### ISSUE THREAD

**Issue by Endemoniada** [atom/language-yaml#55] opened 2016-10-07 06:29 UTC
Entering the Settings page, the "tab length" value is already configured as "4". If I change it to "2", it _immediately_ resets to "4" again. If I remove the value altogether and enter nothing, it says "Default: 2"
Whether or not I leave it empty (default) or set it to 4, it will use 4 spaces. I can seemingly only change the tab length using the Atom global tab length setting, which then changes it for all languages everywhere.

The package is version 0.26.0

**Comment by Ben3eeE** [comment] 2016-10-07 06:37
This is a duplicate of https://github.com/atom/settings-view/issues/774 and will be fixed in Atom 1.12.

**Closed by Ben3eeE** 2016-10-07 06:37 UTC
